// Code generated by hertztool

package main

import (
	"code.byted.org/middleware/hertz/pkg/app/server"
	"github.com/dirac-lee/ddd_demo_parking/biz/handler"
)

// register register routes based on the IDL 'api.${HTTP Method}' annotation.
func register(r *server.Hertz) {
	//INSERT POINT: DO NOT CHANGE NEXT LINE!
	customizeRegister(r)

	r.GET("/ping", handler.Ping)
	{
		_api := r.Group("/api", _api_mws()...)
		{
			_ddd := _api.Group("/ddd", _api_ddd_mws()...)
			{
				_demo := _ddd.Group("/demo", _api_ddd_demo_mws()...)
				{
					_parking := _demo.Group("/parking", _api_ddd_demo_parking_mws()...)
					_parking.POST("/calculate_fee", append(_CalculateFee_mws(), handler.CalculateFee)...)
					_parking.POST("/check_in", append(_CheckIn_mws(), handler.CheckIn)...)
					_parking.POST("/check_out", append(_CheckOut_mws(), handler.CheckOut)...)
					_parking.GET("/daily_revenue", append(_GetDailyRevenue_mws(), handler.GetDailyRevenue)...)
					_parking.GET("/history", append(_GetHistory_mws(), handler.GetHistory)...)
					_parking.POST("/notify_paid", append(_NotifyPaid_mws(), handler.NotifyPaid)...)
					_parking.GET("/total_in_park", append(_GetTotalInPark_mws(), handler.GetTotalInPark)...)
				}
			}
		}
	}
}
