// Code generated by hertztool
package main

import (
	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz/pkg/app/server"
	// "github.com/dirac-lee/ddd_demo_parking/biz/handler"
)

// customizeRegister register customize routers.
func customizeRegister(r *server.Hertz) {
	// your code ...
}

func _api_mws() []app.HandlerFunc {
	return nil
}

func _api_ddd_mws() []app.HandlerFunc {
	return nil
}

func _api_ddd_demo_mws() []app.HandlerFunc {
	return nil
}

func _api_ddd_demo_parking_mws() []app.HandlerFunc {
	return nil
}

func _CalculateFee_mws() []app.HandlerFunc {
	return nil
}

func _CheckIn_mws() []app.HandlerFunc {
	return nil
}

func _CheckOut_mws() []app.HandlerFunc {
	return nil
}

func _NotifyPaid_mws() []app.HandlerFunc {
	return nil
}

func _GetDailyRevenue_mws() []app.HandlerFunc {
	return nil
}

func _GetHistory_mws() []app.HandlerFunc {
	return nil
}

func _GetTotalInPark_mws() []app.HandlerFunc {
	return nil
}
