// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameParkingViewPo = "parking_view"

// ParkingViewPo Parking
type ParkingViewPo struct {
	ID           int64      `gorm:"column:id;primaryKey" json:"id"`
	Plate        string     `gorm:"column:plate;not null" json:"plate"`
	CheckInTime  time.Time  `gorm:"column:check_in_time;not null;default:CURRENT_TIMESTAMP" json:"check_in_time"`
	CheckOutTime *time.Time `gorm:"column:check_out_time" json:"check_out_time"`
	PayAmount    int64      `gorm:"column:pay_amount;not null" json:"pay_amount"`
}

// TableName ParkingViewPo's table name
func (*ParkingViewPo) TableName() string {
	return TableNameParkingViewPo
}
