// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameParkingPo = "parking"

// ParkingPo Parking
type ParkingPo struct {
	ID          string     `gorm:"column:id;primaryKey" json:"id"`
	CheckInTime *time.Time `gorm:"column:check_in_time" json:"check_in_time"`
	LastPayTime *time.Time `gorm:"column:last_pay_time" json:"last_pay_time"`
	TotalPaid   int64      `gorm:"column:total_paid;not null" json:"total_paid"`
}

// TableName ParkingPo's table name
func (*ParkingPo) TableName() string {
	return TableNameParkingPo
}
