// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSummaryPo = "summary"

// SummaryPo mapped from table <summary>
type SummaryPo struct {
	ID             int64 `gorm:"column:id;not null" json:"id"`
	TotalInParking int64 `gorm:"column:total_in_parking;not null" json:"total_in_parking"`
}

// TableName SummaryPo's table name
func (*SummaryPo) TableName() string {
	return TableNameSummaryPo
}
