// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.17.3
// source: ddd_demo_parking.proto

package ddd_demo_parking

import (
	reflect "reflect"
	sync "sync"

	_ "github.com/dirac-lee/ddd_demo_parking/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckInRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarPlate *string `form:"car_plate,required" json:"car_plate,required" protobuf:"bytes,1,req,name=car_plate,json=carPlate" query:"car_plate,required"`
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{0}
}

func (x *CheckInRequest) GetCarPlate() string {
	if x != nil && x.CarPlate != nil {
		return *x.CarPlate
	}
	return ""
}

type CheckInResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *CheckInResponseData `form:"data" json:"data,omitempty" protobuf:"bytes,1,opt,name=data" query:"data"`
	Code    *int32               `form:"code,required" json:"code,required" protobuf:"varint,254,req,name=code" query:"code,required"`
	Message *string              `form:"message,required" json:"message,required" protobuf:"bytes,255,req,name=message" query:"message,required"`
}

func (x *CheckInResponse) Reset() {
	*x = CheckInResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInResponse) ProtoMessage() {}

func (x *CheckInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInResponse.ProtoReflect.Descriptor instead.
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{1}
}

func (x *CheckInResponse) GetData() *CheckInResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CheckInResponse) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *CheckInResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type CheckInResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success *bool `form:"success,required" json:"success,required" protobuf:"varint,1,req,name=success" query:"success,required"`
}

func (x *CheckInResponseData) Reset() {
	*x = CheckInResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckInResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInResponseData) ProtoMessage() {}

func (x *CheckInResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInResponseData.ProtoReflect.Descriptor instead.
func (*CheckInResponseData) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{2}
}

func (x *CheckInResponseData) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

type CheckOutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarPlate *string `form:"car_plate,required" json:"car_plate,required" protobuf:"bytes,1,req,name=car_plate,json=carPlate" query:"car_plate,required"`
}

func (x *CheckOutRequest) Reset() {
	*x = CheckOutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutRequest) ProtoMessage() {}

func (x *CheckOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutRequest.ProtoReflect.Descriptor instead.
func (*CheckOutRequest) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{3}
}

func (x *CheckOutRequest) GetCarPlate() string {
	if x != nil && x.CarPlate != nil {
		return *x.CarPlate
	}
	return ""
}

type CheckOutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *CheckOutResponseData `form:"data" json:"data,omitempty" protobuf:"bytes,1,opt,name=data" query:"data"`
	Code    *int32                `form:"code,required" json:"code,required" protobuf:"varint,254,req,name=code" query:"code,required"`
	Message *string               `form:"message,required" json:"message,required" protobuf:"bytes,255,req,name=message" query:"message,required"`
}

func (x *CheckOutResponse) Reset() {
	*x = CheckOutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutResponse) ProtoMessage() {}

func (x *CheckOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutResponse.ProtoReflect.Descriptor instead.
func (*CheckOutResponse) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{4}
}

func (x *CheckOutResponse) GetData() *CheckOutResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CheckOutResponse) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *CheckOutResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type CheckOutResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success *bool `form:"success,required" json:"success,required" protobuf:"varint,1,req,name=success" query:"success,required"`
}

func (x *CheckOutResponseData) Reset() {
	*x = CheckOutResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckOutResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutResponseData) ProtoMessage() {}

func (x *CheckOutResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutResponseData.ProtoReflect.Descriptor instead.
func (*CheckOutResponseData) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{5}
}

func (x *CheckOutResponseData) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

type CalculateFeeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarPlate *string `form:"car_plate,required" json:"car_plate,required" protobuf:"bytes,1,req,name=car_plate,json=carPlate" query:"car_plate,required"`
}

func (x *CalculateFeeRequest) Reset() {
	*x = CalculateFeeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateFeeRequest) ProtoMessage() {}

func (x *CalculateFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateFeeRequest.ProtoReflect.Descriptor instead.
func (*CalculateFeeRequest) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{6}
}

func (x *CalculateFeeRequest) GetCarPlate() string {
	if x != nil && x.CarPlate != nil {
		return *x.CarPlate
	}
	return ""
}

type CalculateFeeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *CalculateFeeResponseData `form:"data" json:"data,omitempty" protobuf:"bytes,1,opt,name=data" query:"data"`
	Code    *int32                    `form:"code,required" json:"code,required" protobuf:"varint,254,req,name=code" query:"code,required"`
	Message *string                   `form:"message,required" json:"message,required" protobuf:"bytes,255,req,name=message" query:"message,required"`
}

func (x *CalculateFeeResponse) Reset() {
	*x = CalculateFeeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateFeeResponse) ProtoMessage() {}

func (x *CalculateFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateFeeResponse.ProtoReflect.Descriptor instead.
func (*CalculateFeeResponse) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{7}
}

func (x *CalculateFeeResponse) GetData() *CalculateFeeResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CalculateFeeResponse) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *CalculateFeeResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type CalculateFeeResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fee *int64 `form:"fee,required" json:"fee,required" protobuf:"varint,1,req,name=fee" query:"fee,required"`
}

func (x *CalculateFeeResponseData) Reset() {
	*x = CalculateFeeResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateFeeResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateFeeResponseData) ProtoMessage() {}

func (x *CalculateFeeResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateFeeResponseData.ProtoReflect.Descriptor instead.
func (*CalculateFeeResponseData) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{8}
}

func (x *CalculateFeeResponseData) GetFee() int64 {
	if x != nil && x.Fee != nil {
		return *x.Fee
	}
	return 0
}

type NotifyPaidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarPlate  *string `form:"car_plate,required" json:"car_plate,required" protobuf:"bytes,1,req,name=car_plate,json=carPlate" query:"car_plate,required"`
	PayAmount *int64  `form:"pay_amount,required" json:"pay_amount,required" protobuf:"varint,2,req,name=pay_amount,json=payAmount" query:"pay_amount,required"`
}

func (x *NotifyPaidRequest) Reset() {
	*x = NotifyPaidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyPaidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPaidRequest) ProtoMessage() {}

func (x *NotifyPaidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPaidRequest.ProtoReflect.Descriptor instead.
func (*NotifyPaidRequest) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{9}
}

func (x *NotifyPaidRequest) GetCarPlate() string {
	if x != nil && x.CarPlate != nil {
		return *x.CarPlate
	}
	return ""
}

func (x *NotifyPaidRequest) GetPayAmount() int64 {
	if x != nil && x.PayAmount != nil {
		return *x.PayAmount
	}
	return 0
}

type NotifyPaidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *NotifyPaidResponseData `form:"data" json:"data,omitempty" protobuf:"bytes,1,opt,name=data" query:"data"`
	Code    *int32                  `form:"code,required" json:"code,required" protobuf:"varint,254,req,name=code" query:"code,required"`
	Message *string                 `form:"message,required" json:"message,required" protobuf:"bytes,255,req,name=message" query:"message,required"`
}

func (x *NotifyPaidResponse) Reset() {
	*x = NotifyPaidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyPaidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPaidResponse) ProtoMessage() {}

func (x *NotifyPaidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPaidResponse.ProtoReflect.Descriptor instead.
func (*NotifyPaidResponse) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{10}
}

func (x *NotifyPaidResponse) GetData() *NotifyPaidResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *NotifyPaidResponse) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *NotifyPaidResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type NotifyPaidResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success *bool `form:"success,required" json:"success,required" protobuf:"varint,1,req,name=success" query:"success,required"`
}

func (x *NotifyPaidResponseData) Reset() {
	*x = NotifyPaidResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyPaidResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPaidResponseData) ProtoMessage() {}

func (x *NotifyPaidResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPaidResponseData.ProtoReflect.Descriptor instead.
func (*NotifyPaidResponseData) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{11}
}

func (x *NotifyPaidResponseData) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{12}
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *GetHistoryResponseData `form:"data" json:"data,omitempty" protobuf:"bytes,1,opt,name=data" query:"data"`
	Code    *int32                  `form:"code,required" json:"code,required" protobuf:"varint,254,req,name=code" query:"code,required"`
	Message *string                 `form:"message,required" json:"message,required" protobuf:"bytes,255,req,name=message" query:"message,required"`
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{13}
}

func (x *GetHistoryResponse) GetData() *GetHistoryResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetHistoryResponse) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *GetHistoryResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type GetHistoryResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParkingRecords []*ParkingRecord `form:"parking_records" json:"parking_records,omitempty" protobuf:"bytes,1,rep,name=parking_records,json=parkingRecords" query:"parking_records"`
}

func (x *GetHistoryResponseData) Reset() {
	*x = GetHistoryResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHistoryResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponseData) ProtoMessage() {}

func (x *GetHistoryResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponseData.ProtoReflect.Descriptor instead.
func (*GetHistoryResponseData) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{14}
}

func (x *GetHistoryResponseData) GetParkingRecords() []*ParkingRecord {
	if x != nil {
		return x.ParkingRecords
	}
	return nil
}

type ParkingRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarPlate          *string `form:"car_plate,required" json:"car_plate,required" protobuf:"bytes,1,req,name=car_plate,json=carPlate" query:"car_plate,required"`
	CheckInTimestamp  *int64  `form:"check_in_timestamp,required" json:"check_in_timestamp,required" protobuf:"varint,2,req,name=check_in_timestamp,json=checkInTimestamp" query:"check_in_timestamp,required"`
	CheckOutTimestamp *int64  `form:"check_out_timestamp" json:"check_out_timestamp,omitempty" protobuf:"varint,3,opt,name=check_out_timestamp,json=checkOutTimestamp" query:"check_out_timestamp"`
	PayAmount         *int64  `form:"pay_amount,required" json:"pay_amount,required" protobuf:"varint,4,req,name=pay_amount,json=payAmount" query:"pay_amount,required"`
}

func (x *ParkingRecord) Reset() {
	*x = ParkingRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParkingRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkingRecord) ProtoMessage() {}

func (x *ParkingRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkingRecord.ProtoReflect.Descriptor instead.
func (*ParkingRecord) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{15}
}

func (x *ParkingRecord) GetCarPlate() string {
	if x != nil && x.CarPlate != nil {
		return *x.CarPlate
	}
	return ""
}

func (x *ParkingRecord) GetCheckInTimestamp() int64 {
	if x != nil && x.CheckInTimestamp != nil {
		return *x.CheckInTimestamp
	}
	return 0
}

func (x *ParkingRecord) GetCheckOutTimestamp() int64 {
	if x != nil && x.CheckOutTimestamp != nil {
		return *x.CheckOutTimestamp
	}
	return 0
}

func (x *ParkingRecord) GetPayAmount() int64 {
	if x != nil && x.PayAmount != nil {
		return *x.PayAmount
	}
	return 0
}

type GetTotalInParkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTotalInParkRequest) Reset() {
	*x = GetTotalInParkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTotalInParkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalInParkRequest) ProtoMessage() {}

func (x *GetTotalInParkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalInParkRequest.ProtoReflect.Descriptor instead.
func (*GetTotalInParkRequest) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{16}
}

type GetTotalInParkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *GetTotalInParkResponseData `form:"data" json:"data,omitempty" protobuf:"bytes,1,opt,name=data" query:"data"`
	Code    *int32                      `form:"code,required" json:"code,required" protobuf:"varint,254,req,name=code" query:"code,required"`
	Message *string                     `form:"message,required" json:"message,required" protobuf:"bytes,255,req,name=message" query:"message,required"`
}

func (x *GetTotalInParkResponse) Reset() {
	*x = GetTotalInParkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTotalInParkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalInParkResponse) ProtoMessage() {}

func (x *GetTotalInParkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalInParkResponse.ProtoReflect.Descriptor instead.
func (*GetTotalInParkResponse) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{17}
}

func (x *GetTotalInParkResponse) GetData() *GetTotalInParkResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetTotalInParkResponse) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *GetTotalInParkResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type GetTotalInParkResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalInPark *int64 `form:"total_in_park,required" json:"total_in_park,required" protobuf:"varint,1,req,name=total_in_park,json=totalInPark" query:"total_in_park,required"`
}

func (x *GetTotalInParkResponseData) Reset() {
	*x = GetTotalInParkResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTotalInParkResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalInParkResponseData) ProtoMessage() {}

func (x *GetTotalInParkResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalInParkResponseData.ProtoReflect.Descriptor instead.
func (*GetTotalInParkResponseData) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{18}
}

func (x *GetTotalInParkResponseData) GetTotalInPark() int64 {
	if x != nil && x.TotalInPark != nil {
		return *x.TotalInPark
	}
	return 0
}

type GetDailyRevenueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDailyRevenueRequest) Reset() {
	*x = GetDailyRevenueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDailyRevenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyRevenueRequest) ProtoMessage() {}

func (x *GetDailyRevenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyRevenueRequest.ProtoReflect.Descriptor instead.
func (*GetDailyRevenueRequest) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{19}
}

type GetDailyRevenueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *GetDailyRevenueResponseData `form:"data" json:"data,omitempty" protobuf:"bytes,1,opt,name=data" query:"data"`
	Code    *int32                       `form:"code,required" json:"code,required" protobuf:"varint,254,req,name=code" query:"code,required"`
	Message *string                      `form:"message,required" json:"message,required" protobuf:"bytes,255,req,name=message" query:"message,required"`
}

func (x *GetDailyRevenueResponse) Reset() {
	*x = GetDailyRevenueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDailyRevenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyRevenueResponse) ProtoMessage() {}

func (x *GetDailyRevenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyRevenueResponse.ProtoReflect.Descriptor instead.
func (*GetDailyRevenueResponse) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{20}
}

func (x *GetDailyRevenueResponse) GetData() *GetDailyRevenueResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetDailyRevenueResponse) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *GetDailyRevenueResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type GetDailyRevenueResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DailyRevenues []*DailyRevenue `form:"daily_revenues" json:"daily_revenues,omitempty" protobuf:"bytes,1,rep,name=daily_revenues,json=dailyRevenues" query:"daily_revenues"`
}

func (x *GetDailyRevenueResponseData) Reset() {
	*x = GetDailyRevenueResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDailyRevenueResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyRevenueResponseData) ProtoMessage() {}

func (x *GetDailyRevenueResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyRevenueResponseData.ProtoReflect.Descriptor instead.
func (*GetDailyRevenueResponseData) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{21}
}

func (x *GetDailyRevenueResponseData) GetDailyRevenues() []*DailyRevenue {
	if x != nil {
		return x.DailyRevenues
	}
	return nil
}

type DailyRevenue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date    *string `form:"date,required" json:"date,required" protobuf:"bytes,1,req,name=date" query:"date,required"`
	Revenue *int64  `form:"revenue,required" json:"revenue,required" protobuf:"varint,2,req,name=revenue" query:"revenue,required"`
}

func (x *DailyRevenue) Reset() {
	*x = DailyRevenue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddd_demo_parking_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailyRevenue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyRevenue) ProtoMessage() {}

func (x *DailyRevenue) ProtoReflect() protoreflect.Message {
	mi := &file_ddd_demo_parking_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyRevenue.ProtoReflect.Descriptor instead.
func (*DailyRevenue) Descriptor() ([]byte, []int) {
	return file_ddd_demo_parking_proto_rawDescGZIP(), []int{22}
}

func (x *DailyRevenue) GetDate() string {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return ""
}

func (x *DailyRevenue) GetRevenue() int64 {
	if x != nil && x.Revenue != nil {
		return *x.Revenue
	}
	return 0
}

var File_ddd_demo_parking_proto protoreflect.FileDescriptor

var file_ddd_demo_parking_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x64, 0x64, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x5f, 0x70, 0x61, 0x72, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x64, 0x64, 0x64, 0x2e, 0x64, 0x65,
	0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x1a, 0x34, 0x63, 0x6f, 0x64, 0x65,
	0x2e, 0x62, 0x79, 0x74, 0x65, 0x64, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x6f, 0x65, 0x63, 0x2f, 0x68,
	0x74, 0x74, 0x70, 0x5f, 0x69, 0x64, 0x6c, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x62, 0x5f, 0x67,
	0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x2d, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x72, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x22,
	0x7c, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x39, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x64, 0x64, 0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b,
	0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x13, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xfe, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0xff, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2f, 0x0a,
	0x13, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2e,
	0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x72, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x22, 0x7e,
	0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x64, 0x64, 0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b,
	0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x13,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xfe, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0xff,
	0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x30,
	0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x22, 0x32, 0x0a, 0x13, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x5f, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x72, 0x50,
	0x6c, 0x61, 0x74, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x14, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x65, 0x46, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x64, 0x64,
	0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x13, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xfe, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0xff, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2c, 0x0a,
	0x18, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x03, 0x66, 0x65, 0x65, 0x22, 0x4f, 0x0a, 0x11, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x61, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x72, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x61, 0x79, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x03, 0x52, 0x09, 0x70, 0x61, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x82, 0x01, 0x0a,
	0x12, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x61, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x64, 0x64, 0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x61, 0x69, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x13, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xfe, 0x01, 0x20, 0x02, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0xff, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x32, 0x0a, 0x16, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x61, 0x69, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x82, 0x01, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x28, 0x2e, 0x64, 0x64, 0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x13, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xfe, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0xff, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x62, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x48, 0x0a, 0x0f, 0x70, 0x61, 0x72,
	0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x64, 0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61,
	0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x0e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x22, 0xa9, 0x01, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x72, 0x50, 0x6c, 0x61,
	0x74, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x69, 0x6e, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x10,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x2e, 0x0a, 0x13, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x6f, 0x75, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x79, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x02, 0x28, 0x03, 0x52, 0x09, 0x70, 0x61, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x50, 0x61, 0x72,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8a, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x50, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2c, 0x2e, 0x64, 0x64, 0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x50,
	0x61, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x13, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xfe, 0x01,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0xff, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x40, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x49, 0x6e, 0x50, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x5f,
	0x70, 0x61, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x49, 0x6e, 0x50, 0x61, 0x72, 0x6b, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x44, 0x61,
	0x69, 0x6c, 0x79, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x8c, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x65,
	0x76, 0x65, 0x6e, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x64, 0x64,
	0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x13, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xfe, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0xff, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x64, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x76, 0x65,
	0x6e, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x45, 0x0a, 0x0e, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x5f, 0x72, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x64, 0x64, 0x2e, 0x64, 0x65,
	0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x61, 0x69, 0x6c, 0x79,
	0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x52, 0x0d, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x65,
	0x76, 0x65, 0x6e, 0x75, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x0c, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52,
	0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65,
	0x76, 0x65, 0x6e, 0x75, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x76,
	0x65, 0x6e, 0x75, 0x65, 0x32, 0xe3, 0x07, 0x0a, 0x15, 0x44, 0x64, 0x64, 0x44, 0x65, 0x6d, 0x6f,
	0x50, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7a,
	0x0a, 0x07, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x12, 0x20, 0x2e, 0x64, 0x64, 0x64, 0x2e,
	0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x64, 0x64,
	0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a,
	0xd2, 0xc1, 0x18, 0x1e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x64, 0x64, 0x2f, 0x64, 0x65, 0x6d,
	0x6f, 0x2f, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f,
	0x69, 0x6e, 0x92, 0xc8, 0x18, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x12, 0x7e, 0x0a, 0x08, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x12, 0x21, 0x2e, 0x64, 0x64, 0x64, 0x2e, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x64, 0x64, 0x64, 0x2e,
	0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2b, 0xd2,
	0xc1, 0x18, 0x1f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x64, 0x64, 0x2f, 0x64, 0x65, 0x6d, 0x6f,
	0x2f, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x6f,
	0x75, 0x74, 0x92, 0xc8, 0x18, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x12, 0x8e, 0x01, 0x0a, 0x0c, 0x43,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x12, 0x25, 0x2e, 0x64, 0x64,
	0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x64, 0x64, 0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61,
	0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x46,
	0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2f, 0xd2, 0xc1, 0x18, 0x23,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x64, 0x64, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x70, 0x61,
	0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x5f,
	0x66, 0x65, 0x65, 0x92, 0xc8, 0x18, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x12, 0x86, 0x01, 0x0a, 0x0a,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x61, 0x69, 0x64, 0x12, 0x23, 0x2e, 0x64, 0x64, 0x64,
	0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x50, 0x61, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x64, 0x64, 0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x61, 0x69, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2d, 0xd2, 0xc1, 0x18, 0x21, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x64, 0x64, 0x64, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67,
	0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x70, 0x61, 0x69, 0x64, 0x92, 0xc8, 0x18, 0x04,
	0x6a, 0x73, 0x6f, 0x6e, 0x12, 0x82, 0x01, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x12, 0x23, 0x2e, 0x64, 0x64, 0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70,
	0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x64, 0x64, 0x64, 0x2e, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x29,
	0xca, 0xc1, 0x18, 0x1d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x64, 0x64, 0x2f, 0x64, 0x65, 0x6d,
	0x6f, 0x2f, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x92, 0xc8, 0x18, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x12, 0x94, 0x01, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x50, 0x61, 0x72, 0x6b, 0x12, 0x27, 0x2e, 0x64,
	0x64, 0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x50, 0x61, 0x72, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x64, 0x64, 0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f,
	0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x49, 0x6e, 0x50, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x2f, 0xca, 0xc1, 0x18, 0x23, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x64, 0x64, 0x2f, 0x64, 0x65,
	0x6d, 0x6f, 0x2f, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x72, 0x6b, 0x92, 0xc8, 0x18, 0x04, 0x6a, 0x73, 0x6f, 0x6e,
	0x12, 0x97, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x76,
	0x65, 0x6e, 0x75, 0x65, 0x12, 0x28, 0x2e, 0x64, 0x64, 0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x69, 0x6c, 0x79,
	0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29,
	0x2e, 0x64, 0x64, 0x64, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2f, 0xca, 0xc1, 0x18, 0x23, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x64, 0x64, 0x64, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x70, 0x61, 0x72,
	0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x5f, 0x72, 0x65, 0x76, 0x65, 0x6e,
	0x75, 0x65, 0x92, 0xc8, 0x18, 0x04, 0x6a, 0x73, 0x6f, 0x6e,
}

var (
	file_ddd_demo_parking_proto_rawDescOnce sync.Once
	file_ddd_demo_parking_proto_rawDescData = file_ddd_demo_parking_proto_rawDesc
)

func file_ddd_demo_parking_proto_rawDescGZIP() []byte {
	file_ddd_demo_parking_proto_rawDescOnce.Do(func() {
		file_ddd_demo_parking_proto_rawDescData = protoimpl.X.CompressGZIP(file_ddd_demo_parking_proto_rawDescData)
	})
	return file_ddd_demo_parking_proto_rawDescData
}

var file_ddd_demo_parking_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_ddd_demo_parking_proto_goTypes = []interface{}{
	(*CheckInRequest)(nil),              // 0: ddd.demo.parking.CheckInRequest
	(*CheckInResponse)(nil),             // 1: ddd.demo.parking.CheckInResponse
	(*CheckInResponseData)(nil),         // 2: ddd.demo.parking.CheckInResponseData
	(*CheckOutRequest)(nil),             // 3: ddd.demo.parking.CheckOutRequest
	(*CheckOutResponse)(nil),            // 4: ddd.demo.parking.CheckOutResponse
	(*CheckOutResponseData)(nil),        // 5: ddd.demo.parking.CheckOutResponseData
	(*CalculateFeeRequest)(nil),         // 6: ddd.demo.parking.CalculateFeeRequest
	(*CalculateFeeResponse)(nil),        // 7: ddd.demo.parking.CalculateFeeResponse
	(*CalculateFeeResponseData)(nil),    // 8: ddd.demo.parking.CalculateFeeResponseData
	(*NotifyPaidRequest)(nil),           // 9: ddd.demo.parking.NotifyPaidRequest
	(*NotifyPaidResponse)(nil),          // 10: ddd.demo.parking.NotifyPaidResponse
	(*NotifyPaidResponseData)(nil),      // 11: ddd.demo.parking.NotifyPaidResponseData
	(*GetHistoryRequest)(nil),           // 12: ddd.demo.parking.GetHistoryRequest
	(*GetHistoryResponse)(nil),          // 13: ddd.demo.parking.GetHistoryResponse
	(*GetHistoryResponseData)(nil),      // 14: ddd.demo.parking.GetHistoryResponseData
	(*ParkingRecord)(nil),               // 15: ddd.demo.parking.ParkingRecord
	(*GetTotalInParkRequest)(nil),       // 16: ddd.demo.parking.GetTotalInParkRequest
	(*GetTotalInParkResponse)(nil),      // 17: ddd.demo.parking.GetTotalInParkResponse
	(*GetTotalInParkResponseData)(nil),  // 18: ddd.demo.parking.GetTotalInParkResponseData
	(*GetDailyRevenueRequest)(nil),      // 19: ddd.demo.parking.GetDailyRevenueRequest
	(*GetDailyRevenueResponse)(nil),     // 20: ddd.demo.parking.GetDailyRevenueResponse
	(*GetDailyRevenueResponseData)(nil), // 21: ddd.demo.parking.GetDailyRevenueResponseData
	(*DailyRevenue)(nil),                // 22: ddd.demo.parking.DailyRevenue
}
var file_ddd_demo_parking_proto_depIdxs = []int32{
	2,  // 0: ddd.demo.parking.CheckInResponse.data:type_name -> ddd.demo.parking.CheckInResponseData
	5,  // 1: ddd.demo.parking.CheckOutResponse.data:type_name -> ddd.demo.parking.CheckOutResponseData
	8,  // 2: ddd.demo.parking.CalculateFeeResponse.data:type_name -> ddd.demo.parking.CalculateFeeResponseData
	11, // 3: ddd.demo.parking.NotifyPaidResponse.data:type_name -> ddd.demo.parking.NotifyPaidResponseData
	14, // 4: ddd.demo.parking.GetHistoryResponse.data:type_name -> ddd.demo.parking.GetHistoryResponseData
	15, // 5: ddd.demo.parking.GetHistoryResponseData.parking_records:type_name -> ddd.demo.parking.ParkingRecord
	18, // 6: ddd.demo.parking.GetTotalInParkResponse.data:type_name -> ddd.demo.parking.GetTotalInParkResponseData
	21, // 7: ddd.demo.parking.GetDailyRevenueResponse.data:type_name -> ddd.demo.parking.GetDailyRevenueResponseData
	22, // 8: ddd.demo.parking.GetDailyRevenueResponseData.daily_revenues:type_name -> ddd.demo.parking.DailyRevenue
	0,  // 9: ddd.demo.parking.DddDemoParkingService.CheckIn:input_type -> ddd.demo.parking.CheckInRequest
	3,  // 10: ddd.demo.parking.DddDemoParkingService.CheckOut:input_type -> ddd.demo.parking.CheckOutRequest
	6,  // 11: ddd.demo.parking.DddDemoParkingService.CalculateFee:input_type -> ddd.demo.parking.CalculateFeeRequest
	9,  // 12: ddd.demo.parking.DddDemoParkingService.NotifyPaid:input_type -> ddd.demo.parking.NotifyPaidRequest
	12, // 13: ddd.demo.parking.DddDemoParkingService.GetHistory:input_type -> ddd.demo.parking.GetHistoryRequest
	16, // 14: ddd.demo.parking.DddDemoParkingService.GetTotalInPark:input_type -> ddd.demo.parking.GetTotalInParkRequest
	19, // 15: ddd.demo.parking.DddDemoParkingService.GetDailyRevenue:input_type -> ddd.demo.parking.GetDailyRevenueRequest
	1,  // 16: ddd.demo.parking.DddDemoParkingService.CheckIn:output_type -> ddd.demo.parking.CheckInResponse
	4,  // 17: ddd.demo.parking.DddDemoParkingService.CheckOut:output_type -> ddd.demo.parking.CheckOutResponse
	7,  // 18: ddd.demo.parking.DddDemoParkingService.CalculateFee:output_type -> ddd.demo.parking.CalculateFeeResponse
	10, // 19: ddd.demo.parking.DddDemoParkingService.NotifyPaid:output_type -> ddd.demo.parking.NotifyPaidResponse
	13, // 20: ddd.demo.parking.DddDemoParkingService.GetHistory:output_type -> ddd.demo.parking.GetHistoryResponse
	17, // 21: ddd.demo.parking.DddDemoParkingService.GetTotalInPark:output_type -> ddd.demo.parking.GetTotalInParkResponse
	20, // 22: ddd.demo.parking.DddDemoParkingService.GetDailyRevenue:output_type -> ddd.demo.parking.GetDailyRevenueResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_ddd_demo_parking_proto_init() }
func file_ddd_demo_parking_proto_init() {
	if File_ddd_demo_parking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ddd_demo_parking_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckInRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckInResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckInResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckOutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckOutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckOutResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateFeeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateFeeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateFeeResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyPaidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyPaidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyPaidResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHistoryResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParkingRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTotalInParkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTotalInParkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTotalInParkResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDailyRevenueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDailyRevenueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDailyRevenueResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddd_demo_parking_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DailyRevenue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ddd_demo_parking_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ddd_demo_parking_proto_goTypes,
		DependencyIndexes: file_ddd_demo_parking_proto_depIdxs,
		MessageInfos:      file_ddd_demo_parking_proto_msgTypes,
	}.Build()
	File_ddd_demo_parking_proto = out.File
	file_ddd_demo_parking_proto_rawDesc = nil
	file_ddd_demo_parking_proto_goTypes = nil
	file_ddd_demo_parking_proto_depIdxs = nil
}
